# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FV5-ZkMPyP0Zka9icKq6qUmqzp8y37KV
"""

import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

print("TensorFlow version:", tf.__version__)



text = """
machine learning is a branch of artificial intelligence
machine learning enables computers to learn from data
deep learning is a part of machine learning
deep learning uses neural networks to learn complex patterns
neural networks are inspired by the human brain
lstm networks are useful for sequential data
lstm networks can remember information for a long time
natural language processing helps computers understand language
natural language processing is used for text prediction
text prediction can be performed using neural networks
"""


text = text.lower()



tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

total_words = len(tokenizer.word_index) + 1

print("Total number of words:", total_words)
print("Word Index:", tokenizer.word_index)



input_sequences = []

for line in text.split("\n"):
    line = line.strip()

    if line:
        token_list = tokenizer.texts_to_sequences([line])[0]


        for i in range(1, len(token_list)):
            n_gram_sequence = token_list[:i + 1]
            input_sequences.append(n_gram_sequence)



max_sequence_len = max(len(seq) for seq in input_sequences)

print("Maximum sequence length:", max_sequence_len)



input_sequences = np.array(
    pad_sequences(
        input_sequences,
        maxlen=max_sequence_len,
        padding='pre'
    )
)



X = input_sequences[:, :-1]
y = input_sequences[:, -1]



y = tf.keras.utils.to_categorical(y, num_classes=total_words)

print("Input shape:", X.shape)
print("Output shape:", y.shape)



model = Sequential([
    Embedding(
        input_dim=total_words,
        output_dim=100,
        input_length=max_sequence_len - 1
    ),

    LSTM(150),

    Dense(total_words, activation='softmax')
])



model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)



model.summary()



print("\nTraining the model...\n")

history = model.fit(
    X,
    y,
    epochs=200,
    verbose=1
)



def predict_next_word(seed_text):
    seed_text = seed_text.lower()

    token_list = tokenizer.texts_to_sequences([seed_text])[0]


    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len - 1,
        padding='pre'
    )


    predicted_probabilities = model.predict(token_list, verbose=0)


    predicted_word_index = np.argmax(predicted_probabilities, axis=-1)[0]


    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word

    return "Unknown"



seed_text = "machine learning is"

predicted_word = predict_next_word(seed_text)

print("\nSeed text:", seed_text)
print("Predicted next word:", predicted_word)

def generate_text(seed_text, next_words=5):

    generated_text = seed_text

    for _ in range(next_words):
        next_word = predict_next_word(generated_text)
        generated_text += " " + next_word

    return generated_text


print("\nGenerated text:")
print(generate_text("machine learning", 5))